fix lint errors

diff --git a/.github/workflows/ci_release.yml b/.github/workflows/ci_release.yml
--- a/.github/workflows/ci_release.yml
+++ b/.github/workflows/ci_release.yml
@@ -51,47 +51,48 @@ jobs:
   #       with:
   #         dockerfile: Dockerfile
   #         # failure-threshold: info
+
   prepare-env:
-      runs-on: "ubuntu-latest"
-      outputs:
-        build_for_pr: ${{ steps.setting_logic.outputs.build_for_pr }}
-        build_for_merge: ${{ steps.setting_logic.outputs.build_for_merge }}
-        not_a_fork: ${{ steps.setting_logic.outputs.not_a_fork }}
-      steps:
-        - name: Checkout
-          uses: "actions/checkout@v4"
+    runs-on: "ubuntu-latest"
+    outputs:
+      build_for_pr: ${{ steps.setting_logic.outputs.build_for_pr }}
+      build_for_merge: ${{ steps.setting_logic.outputs.build_for_merge }}
+      not_a_fork: ${{ steps.setting_logic.outputs.not_a_fork }}
+    steps:
+      - name: Checkout
+        uses: "actions/checkout@v4"
 
-        - name: Add logic to ENV
-          id: setting_logic
-          run: |
-            # yamllint disable
-            echo "build_for_pr=${{ github.event_name == 'pull_request' }}" >> "$GITHUB_OUTPUT"
-            echo "build_for_merge=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v') }}" >> "$GITHUB_OUTPUT"
-            echo "not_a_fork=${{ github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name }}" >> "$GITHUB_OUTPUT"
-            # yamllint enable
+      - name: Add logic to ENV
+        id: setting_logic
+        run: |
+          # yamllint disable
+          echo "build_for_pr=${{ github.event_name == 'pull_request' }}" >> "$GITHUB_OUTPUT"
+          echo "build_for_merge=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v') }}" >> "$GITHUB_OUTPUT"
+          echo "not_a_fork=${{ github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name }}" >> "$GITHUB_OUTPUT"
+          # yamllint enable
 
-    # Log the key inputs to the logic as well a the outputs. We check that
-    # build_for_pr and build_for_merge are never equal as that would indicate a
-    # bug.
-    logic-check:
-      needs: prepare-env
-      runs-on: "ubuntu-latest"
-      steps:
-        - name: Log logic
-          run: |
-            echo "github.event_name: ${{ github.event_name }}"
-            echo "github.ref: ${{ github.ref }}"
-            echo "github.event.pull_request: ${{ toJSON(github.event.pull_request) }}"
-            echo "head repo: ${{ github.event.pull_request.head.repo.full_name }}"
-            echo "base repo: ${{ github.event.pull_request.base.repo.full_name }}"
-            echo "build_for_pr: ${{ needs.prepare-env.outputs.build_for_pr }}"
-            echo "build_for_merge: ${{ needs.prepare-env.outputs.build_for_merge }}"
-            echo "not_a_fork: ${{ needs.prepare-env.outputs.not_a_fork }}"
-        - name: Check logic
-          if: ${{ needs.prepare-env.outputs.build_for_pr == needs.prepare-env.outputs.build_for_merge }}
-          run: |
-            echo "Failing step due to build_for_pr == build_for_merge"
-            exit 1
+  # Log the key inputs to the logic as well a the outputs. We check that
+  # build_for_pr and build_for_merge are never equal as that would indicate a
+  # bug.
+  logic-check:
+    needs: prepare-env
+    runs-on: "ubuntu-latest"
+    steps:
+      - name: Log logic
+        run: |
+          echo "github.event_name: ${{ github.event_name }}"
+          echo "github.ref: ${{ github.ref }}"
+          echo "github.event.pull_request: ${{ toJSON(github.event.pull_request) }}"
+          echo "head repo: ${{ github.event.pull_request.head.repo.full_name }}"
+          echo "base repo: ${{ github.event.pull_request.base.repo.full_name }}"
+          echo "build_for_pr: ${{ needs.prepare-env.outputs.build_for_pr }}"
+          echo "build_for_merge: ${{ needs.prepare-env.outputs.build_for_merge }}"
+          echo "not_a_fork: ${{ needs.prepare-env.outputs.not_a_fork }}"
+      - name: Check logic
+        if: ${{ needs.prepare-env.outputs.build_for_pr == needs.prepare-env.outputs.build_for_merge }}
+        run: |
+          echo "Failing step due to build_for_pr == build_for_merge"
+          exit 1
 
   get_labels:
     runs-on: ubuntu-latest
